### ISSUE TITLE
Error when deploying to netlify

### ISSUE THREAD

**Issue by TheVip** [sagar7993/gatsby-wordpress-typescript-scss-blog#41]
When I deploy the site to netlify, gatsby-source-wordpress gives the error saying can't read property data of undefined.

**Comment by sagar7993** [comment]
You're getting that error because I have used environment variables in the `gatsby-source-wordpress` configuration found in the `gatsby-config.js` file. Please clone this repo locally and set these URL's to a valid URL, then it will work. Apologies for the confusion. Closing this issue for now, but if you get stuck with something or need any other help, feel free to reopen this issue.
